# Generated by Django 2.2.1 on 2019-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coinid', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
