# Generated by Django 2.2.1 on 2019-05-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='description',
        ),
    ]
