# Generated by Django 2.2.1 on 2019-05-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_remove_additional_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.CharField(default='https://assets.coingecko.com/coins/images/7863/large/KnRIPlfh_400x400.jpg?1551233922', max_length=50),
            preserve_default=False,
        ),
    ]
