# Generated by Django 2.2.1 on 2019-05-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_table_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additional',
        ),
    ]
