# Generated by Django 2.2.1 on 2019-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
