# Generated by Django 2.2.1 on 2019-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20190508_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume', models.IntegerField(null=True)),
                ('high_24h', models.FloatField(null=True)),
                ('low_24h', models.FloatField(null=True)),
                ('price_change_24h', models.FloatField(null=True)),
                ('price_change_percentage_24h', models.FloatField(null=True)),
            ],
        ),
    ]
