# Generated by Django 2.2.1 on 2019-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_marketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='high_24h',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='low_24h',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='total_volume',
        ),
    ]
