# Generated by Django 2.2.1 on 2019-05-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20190513_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('thumbimg', models.CharField(max_length=30)),
                ('marketcap', models.FloatField(null=True)),
                ('totalvolume', models.FloatField(null=True)),
                ('price_change', models.FloatField(null=True)),
                ('circulating_supply', models.FloatField(null=True)),
            ],
        ),
    ]
