# Generated by Django 2.2.1 on 2019-05-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_maintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='pricechangepercentage',
            field=models.FloatField(null=True),
        ),
    ]
