# Generated by Django 2.2.1 on 2019-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_maintable_pricechangepercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='coinid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
